## Homework 5

- Student name: Venus Onyango
- Email: vonyango@gmu.edu
- G-number: G01424357

## Imports

In [9]:
import math
import numpy as np

## Question 1

In [28]:
def rel(t, v, c):
    return t * (1 / math.sqrt(1 - (v ** 2) / (c ** 2)))

rel(1, 2, 5)


1.0910894511799618

## Question 2

In [23]:
def calculate_average(numbers):
    return sum(numbers) / len(numbers)

random_numbers = np.random.randint(-10, 11, 1000)
average = calculate_average(random_numbers)
print("The average of the generated numbers is:", average)

# Explanation 
if average == 0:
    print("The result makes sense because the range -10 to 10 is balanced around zero.")
else:
    print("The result can change because of randomness, but it should be near zero after many tries.")


The average of the generated numbers is: 0.218
The result can change because of randomness, but it should be near zero after many tries.


## Question 3

In [26]:
numbers = [41, 33, 11, 9, 7, 11, 21, 19, 7, 11, 6, 9, 30, 24, 1, 5, 7, 4, 35, 3, 35, 1, 18, 38, 11, 9, 11, 7, 9, 33, 11, 3, 40, 16, 11, 1, 33, 7, 29, 9, 7, 11]

unique_values = set(numbers)
for num in unique_values:
    print(num, "appears", numbers.count(num), "times.")


1 appears 3 times.
3 appears 2 times.
4 appears 1 times.
5 appears 1 times.
6 appears 1 times.
7 appears 6 times.
9 appears 5 times.
11 appears 8 times.
16 appears 1 times.
18 appears 1 times.
19 appears 1 times.
21 appears 1 times.
24 appears 1 times.
29 appears 1 times.
30 appears 1 times.
33 appears 3 times.
35 appears 2 times.
38 appears 1 times.
40 appears 1 times.
41 appears 1 times.


## Question 4

In [37]:
def list_stats(numbers):
    return min(numbers), max(numbers), sum(numbers) / len(numbers)

test_lists = [
    [2, -1, 10, 5],
    [10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10],
    [4],
    [1, 1, 2, 3, 5, 8, 13]
]

for numbers in test_lists:
    minimum, maximum, average = list_stats(numbers)
    print(minimum, maximum, average)


-1 10 4.0
-10 10 0.0
4 4 4.0
1 13 4.714285714285714


## Question 5

In [44]:
def separate(arr1, arr2):
    combined = np.append(arr1, arr2)
    odd_values = combined[combined % 2 != 0]
    even_values = combined[combined % 2 == 0]
    return odd_values, even_values

arr1 = np.random.randint(0, 100, 10)
arr2 = np.random.randint(0, 100, 10)

print(arr1)
print(arr2)
print(separate(arr1, arr2))



[14 69 23 73 57  2 83 81 11 74]
[31 81 30 39 78 85 69  5 99 77]
(array([69, 23, 73, 57, 83, 81, 11, 31, 81, 39, 85, 69,  5, 99, 77]), array([14,  2, 74, 30, 78]))
